# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /

# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.7:3306/ww_api?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
#    password: Admin123!
    password: root
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.macw.wwdoc.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: isDel  #全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  config: classpath:logback.xml
  level:
    org.thymeleaf: info



# 七牛密钥，配上自己申请的七牛账号对应的密钥
qiniu:
  AccessKey: iPq9dj6MhD5eljxeQ-7HQ2merNoS1aW1ja_eBbU7
  SecretKey: MBEZwpuIjd3bnVYox6_v6AuJN9mTv_e-A__RWkLF
  # 七牛空间名
  Bucket: wwdoc
  # 外链访问路径
  prefix: http://wwdoc.henaumcw.top/